services:
  # PostgreSQL Database
  db:
    image: postgres:17
    container_name: register_app_db_dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-register_app}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - register_app_network_dev
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: register_app_backend_dev
    environment:
      # Database
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-register_app}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      
      # Server
      PORT: ${PORT:-8001}
      JWT_SECRET: ${JWT_SECRET:-dev_jwt_secret}
      ROUNDS: ${ROUNDS:-10}
      DEFAULT_USER_ACCESS: ${DEFAULT_USER_ACCESS:-admin}
      DEFAULT_USER_2: ${DEFAULT_USER_2:-user}
      ADM_SECRET: ${ADM_SECRET:-dev_admin_secret}
      
      # AWS S3
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION:-us-east-1}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      
      # Backup Configuration
      BACKUP_DIR: /backups
      BACKUP_RETENTION_DAYS: ${BACKUP_RETENTION_DAYS:-30}
      S3_BACKUP_BUCKET: ${S3_BACKUP_BUCKET:-${AWS_BUCKET_NAME}}
      S3_BACKUP_PREFIX: ${S3_BACKUP_PREFIX:-backups}
      ENABLE_DAILY_BACKUP: ${ENABLE_DAILY_BACKUP:-false}
      TZ: ${TZ:-UTC}
      
      # Node Environment
      NODE_ENV: development
    ports:
      - "0.0.0.0:8001:8001"
    depends_on:
      - db
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - register_app_network_dev
    restart: unless-stopped
    command: npm run dev

  # Frontend (Vite Dev Server)
  frontend:
    build:
      context: ./webapp
      dockerfile: Dockerfile.dev
    container_name: register_app_frontend_dev
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8001}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./webapp:/app
      - /app/node_modules
    networks:
      - register_app_network_dev
    restart: unless-stopped

volumes:
  postgres_data_dev:

networks:
  register_app_network_dev:
    driver: bridge 