version: '3.8'
services:
  db:
    image: postgres:17
    container_name: postgres_register_app
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - register_app_network
  
volumes: 
  postgres_data:

networks:
  register_app_network: {}
