version: '3.8'

services:
  frontend:
    build:
      context: ./webapp
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./webapp:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - register_app_network

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=register_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - register_app_network

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=register_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - register_app_network

volumes:
  postgres_data:

networks:
  register_app_network:
    driver: bridge
